module.exports.brands = [
    'Apple',
    'Lenovo',
    'Dell',
    'Asus',
    'Thermaltake',
    'AMD',
    'Intel',
    'Nvidia',
    'Logitech',
    'Kingston',
    'Bequiet',
    'Razer',
    'Corsair',
    'Samsung',
    'LG',
    'Sharp',
    'Phillips',
    'Siemens',
    'Sony',
    'Xbox',
    'Nintendo'
]

module.exports.productNames = [
    'Laptop',
    'Monitor',
    'CPU',
    'GPU',
    'RAM',
    'SSD',
    'Mouse',
    'Mousepad',
    'Keyboard',
    'Case',
    'Speaker',
    'Drive hub',
    'Headphones',
    'Earphones',
    'Cellphone',
    'Television',
    'Router',
    'Switch',
    'Server',
    'Smartphone',
    'Console'
]